[package]
name = "n3v3-typeck"
description = "Type checking for n3v3"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
n3v3-common = { version = "5.0.2", path = "../n3v3-common" }
n3v3-hir = { version = "5.0.2", path = "../n3v3-hir" }
n3v3-diagnostic = { version = "5.0.2", path = "../n3v3-diagnostic" }

[dev-dependencies]
n3v3-parser = { version = "5.0.2", path = "../n3v3-parser" }
