[package]
name = "n3v3-diagnostic"
description = "Diagnostic and error reporting for n3v3"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
n3v3-common = { version = "5.0.3", path = "../n3v3-common" }
ariadne.workspace = true
thiserror.workspace = true
