[package]
name = "n3v3-lsp"
description = "Language Server Protocol implementation for n3v3"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
n3v3-common = { version = "5.0.1", path = "../n3v3-common" }
n3v3-diagnostic = { version = "5.0.1", path = "../n3v3-diagnostic" }
n3v3-hir = { version = "5.0.1", path = "../n3v3-hir" }
n3v3-lexer = { version = "5.0.1", path = "../n3v3-lexer" }
n3v3-syntax = { version = "5.0.1", path = "../n3v3-syntax" }
n3v3-frontend = { version = "5.0.1", path = "../n3v3-frontend" }
n3v3-fmt = { version = "5.0.1", path = "../n3v3-fmt" }
n3v3-parser = { version = "5.0.1", path = "../n3v3-parser" }
n3v3-typeck = { version = "5.0.1", path = "../n3v3-typeck" }

tower-lsp.workspace = true
tokio.workspace = true
async-trait.workspace = true
dashmap.workspace = true
serde.workspace = true
serde_json.workspace = true
