[package]
name = "n3v3-frontend"
description = "Frontend analysis pipeline for n3v3 (parse + lower + type check)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
n3v3-common = { version = "5.0.2", path = "../n3v3-common" }
n3v3-diagnostic = { version = "5.0.2", path = "../n3v3-diagnostic" }
n3v3-parser = { version = "5.0.2", path = "../n3v3-parser" }
n3v3-hir = { version = "5.0.2", path = "../n3v3-hir" }
n3v3-syntax = { version = "5.0.2", path = "../n3v3-syntax" }
n3v3-typeck = { version = "5.0.2", path = "../n3v3-typeck" }
